# Default initial positions for diana7's ros2_control fake system

initial_positions:
  diana7_joint1: 0
  diana7_joint2: 0
  diana7_joint3: 0
  diana7_joint4: 0
  diana7_joint5: 0
  diana7_joint6: 0
  diana7_joint7: 0