# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - diana7_arm_controller

  diana7_arm_controller:
    type: FollowJointTrajectory
    joints:
      - diana7_joint1
      - diana7_joint2
      - diana7_joint3
      - diana7_joint4
      - diana7_joint5
      - diana7_joint6
      - diana7_joint7
    action_ns: follow_joint_trajectory
    default: true